### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by zhampu** [tekeburak/podcast-summarizer#2]
Im getting an error when using it local

**Comment by tekeburak** [comment]
What error are you getting? Please, give more info about it.

**Comment by zhampu** [comment]
<img width="1848" alt="Screenshot 2024-05-30 at 14 39 38" src="https://github.com/tekeburak/podcast-summarizer/assets/10797660/4f4995fd-ab78-4caf-a22a-3a90cde02ac9">


when I add an rss feed it gives me this error

**Comment by tekeburak** [comment]
I cannot see the screenshot.

**Comment by zhampu** [comment]
Now?

**Comment by tekeburak** [comment]
> <img alt="Screenshot 2024-05-30 at 14 39 38" width="1848" src="https://private-user-images.githubusercontent.com/10797660/335185573-4f4995fd-ab78-4caf-a22a-3a90cde02ac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzM3MjMsIm5iZiI6MTcxNzA3MzQyMywicGF0aCI6Ii8xMDc5NzY2MC8zMzUxODU1NzMtNGY0OTk1ZmQtYWI3OC00Y2FmLWEyMmEtM2E5MGNkZTAyYWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDEyNTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NTBjOTk5MDlhNjJiY2ExOGZlNjU5OTFjNjdiYzhjNDQ5Mjg3NzZiZjkxMzFiM2Q0ZDA5MzlkOTg5MzFiM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ima7qEB5HKdR_y2IiEBzU7D0VURhrzqGUTTYqkFHzGg">
> 
> when I add an rss feed it gives me this error

It says there is a credential missing error. You need to make settings for credential.
Please naviagate to the Manage Accounts section of your profile and look-up the Usage tab on OpenAI platform page.
And visit the API Keys tab and Create a new secret key and copy this and keep it available. You need to create a secret called `my-openai-secret` on **Modal**, enter the secret you received from OpenAI to the **Modal**'s secret section

In addition, you need to set the TOKEN_ID and TOKEN_SECRET for deploying on Modal.

`modal token new --source podcast > authenticationURL.txt`
When you run the command, it creates a file in your environment which contains the URL. You can open it and you can follow the link by doing a click. This will activate your account with Modal!
Once you have completed sign-in, please navigate to the Settings tab and then API Tokens on modal.com. Please click on Create Token and then you should see a window pop-up with a command that you can copy.

The command will have a format as follows:
`modal token set --token-id TOKEN_ID --token-secret TOKEN_SECRET`

And then deploy the backend to the modal with the following code.
`modal deploy /content/podcast/podcast_backend.py`

You also need to set MODAL_TOKEN_ID and MODAL_TOKEN_SECRET as local parameters for the Streamlit side to work properly.

**Comment by zhampu** [comment]
So I have alreadz my api key. Could you please be more specfic on this part:
"ou need to create a secret called my-openai-secret on Modal, enter the secret you received from OpenAI to the Modal's secret section"

perhaps you can put which commands are in modal to do this?

**Comment by tekeburak** [comment]
> So I have alreadz my api key. Could you please be more specfic on this part: "ou need to create a secret called my-openai-secret on Modal, enter the secret you received from OpenAI to the Modal's secret section"
> 
> perhaps you can put which commands are in modal to do this?


I am not sure there is a command for it but it's on modal.com website Dashboard section.

`Secrets > Create new secret` and set the secret name as `my-openai-secret`.

https://github.com/tekeburak/podcast-summarizer/blob/c7d92b478d27304ba2c8ea858bab290712c37269/content/podcast/podcast_backend.py#L103

**Comment by zhampu** [comment]
<img width="490" alt="Screenshot 2024-05-30 at 15 58 37" src="https://github.com/tekeburak/podcast-summarizer/assets/10797660/aba802ed-9f2a-4e55-8f25-027019ec3087">

for reason Modal does not allow me to name it like you said... any hints why?

**Comment by tekeburak** [comment]
> <img alt="Screenshot 2024-05-30 at 15 58 37" width="490" src="https://private-user-images.githubusercontent.com/10797660/335211735-aba802ed-9f2a-4e55-8f25-027019ec3087.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzgxMjEsIm5iZiI6MTcxNzA3NzgyMSwicGF0aCI6Ii8xMDc5NzY2MC8zMzUyMTE3MzUtYWJhODAyZWQtOWYyYS00ZTU1LThmMjUtMDI3MDE5ZWMzMDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDE0MDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2NzZiNDRkNTM5MDUzZGFkNmFlMDc5YzZiMzY0MTU2OTZkYWJkZTUyYjg0NWE1NzU1NjhiOWVjNTYwNzNhNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EUeq89sda0g-4JzEwjcZv7r8WmXmczOe-aosDD9HniU">
> 
> for reason Modal does not allow me to name it like you said... any hints why?

They seem to have changed the naming format. You can use a different name, but you need to change the all `my-openai-secret` parameter in the backend file.

https://github.com/tekeburak/podcast-summarizer/blob/main/content/podcast/podcast_backend.py

**Comment by zhampu** [comment]
Model backend is running however im getting an error, but that might be linked to the RSS url im using.

could you send an RSS url that you have tested that works?

**Comment by tekeburak** [comment]
> Model backend is running however im getting an error, but that might be linked to the RSS url im using.
> 
> could you send an RSS url that you have tested that works?

You can use [Technology Untangled RSS.](https://feeds.transistor.fm/technology-untangled)
